# 在使用前请先阅读 README.md
# Please read README.md before use this theme

# favicon.ico 和 icon.png 都存放在 source 文件夹中
# "favicon.ico" and "icon.png" are stored in "source" folder
favicon: favicon.ico
icon: icon.png

# 作者简介，内容会显示在 about 页面上
# author descriptions, all these information will be displayed on about page
author:
  github: "src_resources"
  email: "src.res.211@gmail.com"
  telegram: ""
  instagram: ""
  twitter: ""
  weibo: ""
  zhihu: ""
  youtube: ""

# 目前仅提供cc协议
# currently only proviede cc
copyright:
  # 显示版权信息，0为关闭，1为对所有post生效，2为对文章中有"copyright: true"的文章才生效
  # Show copyright info, 0 for close, 1 for all posts, 2 for all posts with "copyright: true"
  open: 1
  # 是否可被商用，0为不可，1为可
  # whether can be used commercially, 0 for no, 1 for ok
  commercial: 0
  # 是否可被演绎，0为不可，1为在相同方式下可，2为可
  # whether can be changed, 0 for no, 2 for ok, 1 for ok in the same circumstance
  derivative: 1

comment:
  Select:

# 友链
# friendlink
friendlink:
  enable: false
  links:

# 网站成立时间，若大于等于当前年份则不会显示
# The start year of the site which won't be shown if is beyond current
startYear: 2024

# 显示页脚主题信息
# show theme info
showTheme: false

# 不蒜子网页统计
# busuanzi
busuanzi:
  enable: false

# 备案
beian:
