on: push

jobs:
    validate:
        name: Validate repo files
        runs-on: ubuntu-latest
        steps:
        - name: Checkout from GitHub repo
          uses: actions/checkout@v4.1.2
        - name: Install npm packages
          run: npm install
        - name: Build the source using npm
          run: npm run build